# Hyper-parameters
bs: 32
lr: 0.0001
wd: 0.0001
epoch: 20
optimizer: Adam
nb_worker: 8
temp: 0.5
lr_decay: keras

# DNN args
m_first_conv: 1024
m_in_channels: 1
m_filts: [20, [20,20], [20,128], [128,128]]
m_blocks: [2, 4]
m_nb_fc_att_node: [1]
m_nb_fc_node: 1024
m_gru_node: 1024
m_nb_gru_layer: 3
m_nb_samp: 64600
m_nb_classes: 2

# Flags
amsgrad: true
multi_gpu: true